// demo-data.js — used ONLY on non-production hosts. Safe to delete entirely
// once real listings are flowing through Decap CMS in production.

export const DEMO_PROPS = [
  {
    _slug: 'harborview-cottage',
    title: 'Harborview Cottage',
    location: 'Old Orchard Beach, ME',
    address: '1 Temple Ave, Old Orchard Beach, ME',
    type: 'Cottage',
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    price: '$2,400',
    photo: '',
    description:
      'A charming shingled cottage steps from the beach. Wrap-around porch, fully equipped kitchen, and ocean breezes all week.',
    tags: ['pet-friendly', 'waterfront'],
    lat: 43.5176,
    lng: -70.3743,
    active: true,
    cleaning_fee: 175,
    pet_fee: 50,
    min_nights: 7,
    availability: [
      { date: '2026-07-04', status: 'available' },
      { date: '2026-07-05', status: 'available' },
      { date: '2026-07-06', status: 'available' },
      { date: '2026-07-07', status: 'available' },
      { date: '2026-07-08', status: 'available' },
      { date: '2026-07-09', status: 'available' },
      { date: '2026-07-10', status: 'available' },
      { date: '2026-08-01', status: 'available' },
      { date: '2026-08-02', status: 'available' },
      { date: '2026-08-03', status: 'available' },
      { date: '2026-08-04', status: 'available' },
      { date: '2026-08-05', status: 'available' },
      { date: '2026-08-06', status: 'available' },
      { date: '2026-08-07', status: 'available' },
      { date: '2026-08-08', status: 'available' },
    ],
  },
  {
    _slug: 'pine-haven-cape',
    title: 'Pine Haven Cape',
    location: 'Saco, ME',
    address: 'Saco, ME',
    type: 'Cape',
    bedrooms: 4,
    bathrooms: 2,
    guests: 8,
    price: '$3,100',
    photo: '',
    description:
      'Classic New England Cape on a quiet street. Big backyard, outdoor shower, bikes included, five minutes to the beach.',
    tags: ['year-round'],
    lat: 43.5009,
    lng: -70.4428,
    active: true,
    cleaning_fee: 200,
    pet_fee: 0,
    min_nights: 7,
    availability: [
      { date: '2026-06-27', status: 'available' },
      { date: '2026-06-28', status: 'available' },
      { date: '2026-06-29', status: 'available' },
      { date: '2026-06-30', status: 'available' },
      { date: '2026-07-01', status: 'available' },
      { date: '2026-07-18', status: 'available' },
      { date: '2026-07-19', status: 'available' },
      { date: '2026-07-20', status: 'available' },
      { date: '2026-07-21', status: 'available' },
      { date: '2026-07-22', status: 'available' },
      { date: '2026-07-23', status: 'available' },
      { date: '2026-07-24', status: 'available' },
    ],
  },
  {
    _slug: 'dune-cottage',
    title: 'The Dune Cottage',
    location: 'Old Orchard Beach, ME',
    address: 'Old Orchard Beach, ME',
    type: 'Cottage',
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    price: '$1,750',
    photo: '',
    description:
      'Cozy cottage tucked in the dunes. Steps to the sand, screened porch, fully stocked. Perfect for a couple or small family.',
    tags: ['waterfront', 'pet-friendly'],
    lat: 43.522,
    lng: -70.38,
    active: true,
    cleaning_fee: 125,
    pet_fee: 50,
    min_nights: 4,
    availability: [
      { date: '2026-07-04', status: 'available' },
      { date: '2026-07-05', status: 'available' },
      { date: '2026-07-06', status: 'available' },
      { date: '2026-07-07', status: 'available' },
      { date: '2026-07-08', status: 'available' },
      { date: '2026-07-09', status: 'available' },
      { date: '2026-07-10', status: 'available' },
      { date: '2026-07-11', status: 'available' },
      { date: '2026-07-12', status: 'available' },
      { date: '2026-07-13', status: 'available' },
      { date: '2026-07-14', status: 'available' },
      { date: '2026-07-15', status: 'available' },
      { date: '2026-07-16', status: 'available' },
      { date: '2026-07-17', status: 'available' },
      { date: '2026-07-18', status: 'available' },
    ],
  },
];

export const DEMO_REVIEWS = [
  {
    property: 'Harborview Cottage',
    author: 'Michelle T.',
    rating: 5,
    text: 'Absolutely perfect week. The cottage was spotless, the porch was our favorite spot every evening. Felt like a home, not a rental.',
    date: 'August 2025',
    approved: true,
  },
  {
    property: 'Pine Haven Cape',
    author: 'David & Sarah R.',
    rating: 5,
    text: "Best vacation rental we've ever stayed in. Incredibly well-maintained, great neighborhood. Already booked next summer.",
    date: 'July 2025',
    approved: true,
  },
  {
    property: 'Harborview Cottage',
    author: 'James P.',
    rating: 4,
    text: 'Beautiful property, great location. The owner was super responsive and helpful. Would highly recommend.',
    date: 'July 2025',
    approved: true,
  },
  {
    property: 'The Dune Cottage',
    author: 'Karen L.',
    rating: 5,
    text: 'Woke up to the sound of waves every morning. Charming and had everything we needed.',
    date: 'August 2025',
    approved: true,
  },
  {
    property: 'Pine Haven Cape',
    author: 'Tom B.',
    rating: 5,
    text: 'Brought the whole extended family. Plenty of space and the backyard was perfect for the kids.',
    date: 'August 2025',
    approved: true,
  },
];

export const DEMO_POSTS = [
  {
    _slug: 'best-beaches-oob',
    title: 'The Best Beaches Around Old Orchard Beach',
    date: 'March 2026',
    excerpt:
      "From the iconic main beach to quieter stretches in Scarborough — here's where locals actually go.",
    emoji: '🏖️',
  },
  {
    _slug: 'oob-lobster-rolls-ranked',
    title: 'The Lobster Roll Situation in OOB',
    date: 'April 2026',
    excerpt: "My completely honest rankings — what's worth your money and what to skip.",
    emoji: '🦞',
  },
];
